; PlatformIO Project Configuration File
;
; Lab2 - Pametni poštanski sandučić
; ESP32 + Arduino framework + Deep Sleep wake-up preko GPIO33

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

